mysite/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from flask_login import login_required, current_user
from models import Team, Tournament, User, Standings, MyModel, Max_rounds_t
from flask_app import db
import json
import requests
import random
import csv
import math
from ast import literal_eval
from datetime import datetime

views = Blueprint('views', __name__)


@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    response = requests.get('https://pavanartim.pythonanywhere.com/')
    ban = response.json().get('data')
    ban2 = response.json()

    shadow_1 = 0
    shadow_2 = 0
    shadow_3 = 0
    shadow_4 = 0
    shadow_5 = 0
    shadow_6 = 0
    shadow_7 = 0
    shadow_8 = 0

    with open("/home/dreeverbeku/mysite/monlist.txt", "r") as file:
        content = file.read()
    options = eval(content)
    filenames = ['1.png','2.png','3.jpeg']
    from models import MyModel
    my_model = MyModel.query.first()
    if not my_model:
        my_model = MyModel(stage='Welcome')
        db.session.add(my_model)
        db.session.commit()
    stage = my_model.stage
    if request.method == 'POST':
            mon1 = request.form.get('mon1')
            mon2 = request.form.get('mon2')
            mon3 = request.form.get('mon3')
            mon4 = request.form.get('mon4')
            mon5 = request.form.get('mon5')
            mon6 = request.form.get('mon6')
            mon7 = request.form.get('mon7')
            mon8 = request.form.get('mon8')

            entered_team = Team.query.filter_by(user_id=current_user.id).first()
            if(entered_team):
                if(mon1):
                    if("shadow" in mon1):
                        entered_team.mon1_shadow = 1
                        shadow_1=1
                    else:
                        entered_team.mon1_shadow = 0
                    mon1 = mon1.replace("_shadow", "")
                    mon1 = mon1.replace("tapu_", "tapu-")
                    entered_team.mon1 = mon1
                if(mon2):
                    if("shadow" in mon2):
                        entered_team.mon2_shadow = 1
                        shadow_2=1
                    else:
                        entered_team.mon2_shadow = 0
                    mon2 = mon2.replace("_shadow", "")
                    mon2 = mon2.replace("tapu_", "tapu-")
                    entered_team.mon2 = mon2
                if(mon3):
                    if("shadow" in mon3):
                        entered_team.mon3_shadow = 1
                        shadow_3=1
                    else:
                        entered_team.mon3_shadow = 0
                    mon3 = mon3.replace("_shadow", "")
                    mon3 = mon3.replace("tapu_", "tapu-")
                    entered_team.mon3 = mon3
                if(mon4):
                    if("shadow" in mon4):
                        entered_team.mon4_shadow = 1
                        shadow_4=1
                    else:
                        entered_team.mon4_shadow = 0
                    mon4 = mon4.replace("_shadow", "")
                    mon4 = mon4.replace("tapu_", "tapu-")
                    entered_team.mon4 = mon4
                if(mon5):
                    if("shadow" in mon5):
                        entered_team.mon5_shadow = 1
                        shadow_5=1
                    else:
                        entered_team.mon5_shadow = 0
                    mon5 = mon5.replace("_shadow", "")
                    mon5 = mon5.replace("tapu_", "tapu-")
                    entered_team.mon5 = mon5
                if(mon6):
                    if("shadow" in mon6):
                        entered_team.mon6_shadow = 1
                        shadow_6=1
                    else:
                        entered_team.mon6_shadow = 0
                    mon6 = mon6.replace("_shadow", "")
                    mon6 = mon6.replace("tapu_", "tapu-")
                    entered_team.mon6 = mon6
                if(mon7):
                    if("shadow" in mon7):
                        entered_team.mon7_shadow = 1
                        shadow_7=1
                    else:
                        entered_team.mon7_shadow = 0
                    mon7 = mon7.replace("_shadow", "")
                    mon7 = mon7.replace("tapu_", "tapu-")
                    entered_team.mon7 = mon7
                if(mon8):
                    if("shadow" in mon8):
                        entered_team.mon8_shadow = 1
                        shadow_8=1
                    else:
                        entered_team.mon8_shadow = 0
                    mon8 = mon8.replace("_shadow", "")
                    mon8 = mon8.replace("tapu_", "tapu-")
                    entered_team.mon8 = mon8
                db.session.commit()
                flash('Team changed!', category='success')
            else:
                if mon1 and mon2 and mon3 and mon4 and mon5 and mon6 and mon7 and mon8:
                    if("shadow" in mon1):
                        shadow_1 = 1
                    if("shadow" in mon2):
                        shadow_2 = 1
                    if("shadow" in mon3):
                        shadow_3 = 1
                    if("shadow" in mon4):
                        shadow_4 = 1
                    if("shadow" in mon5):
                        shadow_5 = 1
                    if("shadow" in mon6):
                        shadow_6 = 1
                    if("shadow" in mon7):
                        shadow_7 = 1
                    if("shadow" in mon8):
                        shadow_8 = 1
                    mon1 = mon1.replace("_shadow", "")
                    mon1 = mon1.replace("tapu_", "tapu-")
                    mon2 = mon2.replace("_shadow", "")
                    mon2 = mon2.replace("tapu_", "tapu-")
                    mon3 = mon3.replace("_shadow", "")
                    mon3 = mon3.replace("tapu_", "tapu-")
                    mon4 = mon4.replace("_shadow", "")
                    mon4 = mon4.replace("tapu_", "tapu-")
                    mon5 = mon5.replace("_shadow", "")
                    mon5 = mon5.replace("tapu_", "tapu-")
                    mon6 = mon6.replace("_shadow", "")
                    mon6 = mon6.replace("tapu_", "tapu-")
                    mon7 = mon7.replace("_shadow", "")
                    mon7 = mon7.replace("tapu_", "tapu-")
                    mon8 = mon8.replace("_shadow", "")
                    mon8 = mon8.replace("tapu_", "tapu-")

                    entered_team = Team(mon1=mon1,mon2=mon2,mon3=mon3,mon4=mon4,mon5=mon5,mon6=mon6,mon7=mon7,mon8=mon8, mon1_shadow=shadow_1,
                    mon2_shadow=shadow_2, mon3_shadow=shadow_3, mon4_shadow=shadow_4, mon5_shadow=shadow_5, mon6_shadow=shadow_6, mon7_shadow=shadow_7, mon8_shadow=shadow_8,user_id=current_user.id)  #providing the schema for the team
                    db.session.add(entered_team)
                    db.session.commit()
                    flash('Team added!', category='success')
                else:
                    flash('Trainer, You need 8 Pokemon to begin!', category='error')
    entered_team = Team.query.filter_by(user_id=current_user.id).first()
    if(entered_team):
        return render_template("home.html", user=current_user, current_stage=stage, options=options, filenames=filenames, zip=zip, str=str, eval=eval, ban=ban, shadow_1=entered_team.mon1_shadow,
        shadow_2=entered_team.mon2_shadow,shadow_3=entered_team.mon3_shadow,shadow_4=entered_team.mon4_shadow,shadow_5=entered_team.mon5_shadow,shadow_6=entered_team.mon6_shadow,shadow_7=entered_team.mon7_shadow,shadow_8=entered_team.mon8_shadow)
    else:
        return render_template("home.html", user=current_user, current_stage=stage, options=options, filenames=filenames, zip=zip, str=str, eval=eval, ban=ban, shadow_1=0,
        shadow_2=0,shadow_3=0,shadow_4=0,shadow_5=0,shadow_6=0,shadow_7=0,shadow_8=0)

def make_team_small():
    users = User.query.all()
    for user in users:
        team = Team.query.filter_by(user_id=user.id).first()
        if team:
            if team.mon1:
                team.mon1 = team.mon1.lower()
            if team.mon2:
                team.mon2 = team.mon2.lower()
            if team.mon3:
                team.mon3 = team.mon3.lower()
            if team.mon4:
                team.mon4 = team.mon4.lower()
            if team.mon5:
                team.mon5 = team.mon5.lower()
            if team.mon6:
                team.mon6 = team.mon6.lower()
            if team.mon7:
                team.mon7 = team.mon7.lower()
            if team.mon8:
                team.mon8 = team.mon8.lower()
        db.session.commit()


@views.route('/delete-team', methods=['POST'])
def delete_team():
    team = json.loads(request.data) # this function expects a JSON from the INDEX.js file
    teamId = team['teamId']
    team = Team.query.get(teamId)
    if team:
        if team.user_id == current_user.id:
            db.session.delete(team)
            db.session.commit()
    return jsonify({})

@views.route('/tournament', methods=['GET','POST'])
@login_required
def tourney():
    my_model = MyModel.query.first()
    stage = my_model.stage
    #hard code for now
    if (stage == 'Welcome'):
        return render_template("tournament_load.html", stage=stage, user=current_user)
    if (stage == 'Battle'):
        player = current_user.first_name
        filename = '/home/dreeverbeku/mysite/pairings.csv'
        pairings = []
        with open(filename, 'r') as file:
            reader = csv.reader(file)
            for row in reader:
                pairings.append(row)
        #set yourelf as opponent to avoid crashing
        opponent = player
        for pairing in pairings:
                if pairing[0] == player:
                    opponent = pairing[1]
                    break
                elif pairing[1] == player:
                    opponent = pairing[0]
                    break

mysite/templates/about.html
<!DOCTYPE html>
<html>
<head>
    <title>Embed External Site</title>
</head>
<body>
    <iframe src="/home/dreeverbeku/mysite/templates/about.php?url=http://project7960408.tilda.ws/" width="100%" height="500"></iframe>
</body>
</html>

mysite/templates/admin.html
{% extends "base.html" %} {% block title %}Admin{% endblock %} {% block content
%}

    {% if current_stage == "Welcome"%}
        <h1 align="center">Begin Tournament</h1>
            <div align="center">
                <form method="post">
                    <button type="submit" class="btn btn-primary" name="my_button" value="Welcome">Battle</button>
                </form>
            </div>
    {% endif %}

    {% if current_stage == "Battle"%}
        <h1 align="center">Restart Check-ins</h1>
            <div align="center">
                <form method="post">
                    <button type="submit" class="btn btn-primary" name="my_button" value="Battle">Welcome</button>
                </form>
            </div>
    {% endif %}

{% endblock %}

mysite/templates/admin_update.html
{% extends "base.html" %} {% block title %}Admin Update{% endblock %} {% block content
%}
    <h1>Data from JSON</h1>
    {% if json_data|length == 0 %}
        <p>No JSON data available.</p>
    {% else %}
        <table border="1">
            <tr>
                <th>Username</th>
                <th>wins</th>
                <th>edit_wins</th>
                <th>Email</th>
                <th>total_wins</th>
                <th>edit_total_wins</th>
                <th>already_matched</th>
                <th>edit_already_matched</th>
                <th>toughness</th>
                <th>edit_toughness</th>
                <th>round_wins</th>
                <th>edit_round_wins</th>
            </tr>
            {% for item in json_data %}
                <tr>
                    <td>{{ item[0] }}</td>
                    <td>{{ item[1] }}</td>
                    <td>
                            <select name="dropdown_{{ loop.index }}">
                                <option value="value1">Option 1</option>
                                <option value="value2">Option 2</option>
                                <option value="value3">Option 3</option>
                            </select>
                    </td>
                    <td>{{ item[2] }}</td>
                    <td>{{ item[3] }}</td>
                    <td>
                            <select name="dropdown_{{ loop.index }}">
                                <option value="value1">Option 1</option>
                                <option value="value2">Option 2</option>
                                <option value="value3">Option 3</option>
                            </select>
                    </td>
                    <td>{{ item[4] }}</td>
                    <td>
                            <select name="dropdown_{{ loop.index }}">
                                <option value="value1">Option 1</option>
                                <option value="value2">Option 2</option>
                                <option value="value3">Option 3</option>
                            </select>
                    </td>
                    <td>{{ item[5] }}</td>
                    <td>
                            <select name="dropdown_{{ loop.index }}">
                                <option value="value1">Option 1</option>
                                <option value="value2">Option 2</option>
                                <option value="value3">Option 3</option>
                            </select>
                    </td>
                    <td>{{ item[6] }}</td>
                    <td>
                            <select name="dropdown_{{ loop.index }}">
                                <option value="value1">Option 1</option>
                                <option value="value2">Option 2</option>
                                <option value="value3">Option 3</option>
                            </select>
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}
{% endblock %}

mysite/templates/nextround.html
{% extends "base.html" %} {% block title %}Admin{% endblock %} {% block content
%}

  <form id="dabba" action="{{ url_for('views.nextround') }}" method="POST">
    <button type="submit">Next Round!</button>
  </form>

{% endblock %}

mysite/templates/tournament.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%}
<style>
.column {
    flex: 1;
    position: relative; /* Add this line */
    }
.column_opp {
    flex: 1;
    position: relative; /* Add this line */
    }
</style>
<h1 align="center">NEW OPPONENT!</h1>
<h2 align="center">Your registered team</h1>
<ul class="list-group list-group-flush" id="teams">
  {% for team in user.teams %}
  <li class="list-group-item">
    {{ team.mon1 }}
    {{ team.mon2 }}
    {{ team.mon3 }}
    {{ team.mon4 }}
    {{ team.mon5 }}
    {{ team.mon6 }}
    {{ team.mon7 }}
    {{ team.mon8 }}
    <div class="image-container">
  <div class="row" style="width: 100%; max-width: 100vw; overflow-x: hidden;">

    <div class="column">
    {% if toban1 == 1 or toban2 == 1%}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon1}}.png" alt="1" style="filter: grayscale(100%);">
    {% else %}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon1}}.png" alt="1">
    {% endif %}
    {% if team.mon1_shadow == 1%}
        <img src="https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Rocket/shadow_icon.png" alt="shadow" style="position: absolute; top: 0; left: 0; opacity: 0.5;">
        {% endif %}
    </div>

    <div class="column">
    {% if toban1 == 2 or toban2 == 2%}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon2}}.png" alt="2" style="filter: grayscale(100%);">
    {% else %}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon2}}.png" alt="2">
    {% endif %}
    {% if team.mon2_shadow == 1%}
        <img src="https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Rocket/shadow_icon.png" alt="shadow" style="position: absolute; top: 0; left: 0; opacity: 0.5;">
        {% endif %}
    </div>

    <div class="column">
    {% if toban1 == 3 or toban2 == 3%}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon3}}.png" alt="3" style="filter: grayscale(100%);">
    {% else %}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon3}}.png" alt="3">
    {% endif %}
    {% if team.mon3_shadow == 1%}
        <img src="https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Rocket/shadow_icon.png" alt="shadow" style="position: absolute; top: 0; left: 0; opacity: 0.5;">
        {% endif %}
    </div>

    <div class="column">
    {% if toban1 == 4 or toban2 == 4%}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon4}}.png" alt="4" style="filter: grayscale(100%);">
    {% else %}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon4}}.png" alt="4">
    {% endif %}
    {% if team.mon4_shadow == 1%}
        <img src="https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Rocket/shadow_icon.png" alt="shadow" style="position: absolute; top: 0; left: 0; opacity: 0.5;">
        {% endif %}
    </div>
  </div>
  <div class="row" style="width: 100%; max-width: 100vw; overflow-x: hidden;">
    <div class="column">
    {% if toban1 == 5 or toban2 == 5%}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon5}}.png" alt="5" style="filter: grayscale(100%);">
    {% else %}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon5}}.png" alt="5">
    {% endif %}
    {% if team.mon5_shadow == 1%}
        <img src="https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Rocket/shadow_icon.png" alt="shadow" style="position: absolute; top: 0; left: 0; opacity: 0.5;">
        {% endif %}
    </div>

    <div class="column">
    {% if toban1 == 6 or toban2 == 6%}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon6}}.png" alt="6" style="filter: grayscale(100%);">
    {% else %}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon6}}.png" alt="6">
    {% endif %}
    {% if team.mon6_shadow == 1%}
        <img src="https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Rocket/shadow_icon.png" alt="shadow" style="position: absolute; top: 0; left: 0; opacity: 0.5;">
        {% endif %}
    </div>

    <div class="column">
    {% if toban1 == 7 or toban2 == 7%}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon7}}.png" alt="7" style="filter: grayscale(100%);">
    {% else %}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon7}}.png" alt="7">
    {% endif %}
    {% if team.mon7_shadow == 1%}
        <img src="https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Rocket/shadow_icon.png" alt="shadow" style="position: absolute; top: 0; left: 0; opacity: 0.5;">
        {% endif %}
    </div>
    <div class="column">
    {% if toban1 == 8 or toban2 == 8%}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon8}}.png" alt="8" style="filter: grayscale(100%);">
    {% else %}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon8}}.png" alt="8">
    {% endif %}
    {% if team.mon8_shadow == 1%}
        <img src="https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Rocket/shadow_icon.png" alt="shadow" style="position: absolute; top: 0; left: 0; opacity: 0.5;">
        {% endif %}
    </div>
  </div>
</div>
{% if ban == 1 %}
    <div class="container" style="position: relative; width: 400px; height: 30px; background-color: white; display: flex; justify-content: center; align-items: center; padding: 20px;">
        <button id="submitBtn" disabled onclick="submitForm1()">Save these Pokemon from ban!</button>
    </div>
{% endif %}
  </li>
  {% endfor %}
</ul>

<h1 align="center">vs.</h1>
<h1 align="center">{{opponent.first_name}}</h1>
<h2 align="center">Wait for your opponent to submit bans, and then Refresh!</h2>
<ul class="list-group list-group-flush" id="teams">
  {% for team in opponent.teams %}
  <li class="list-group-item">
    {{ team.mon1 }}
    {{ team.mon2 }}
    {{ team.mon3 }}
    {{ team.mon4 }}
    {{ team.mon5 }}
    {{ team.mon6 }}
    {{ team.mon7 }}
    {{ team.mon8 }}
    <div class="image-container">
  <div class="row">
    <div class="column_opp">
    {% if oppban1 == 1 or oppban2 == 1%}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon1}}.png" alt="opp_1" style="filter: grayscale(100%);">
    {% else %}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon1}}.png" alt="opp_1">
    {% endif %}
    {% if team.mon1_shadow == 1%}
        <img src="https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Rocket/shadow_icon.png" alt="shadow" style="position: absolute; top: 0; left: 0; opacity: 0.5;">
        {% endif %}
    </div>
    <div class="column_opp">
    {% if oppban1 == 2 or oppban2 == 2%}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon2}}.png" alt="opp_2" style="filter: grayscale(100%);">
    {% else %}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon2}}.png" alt="opp_2">
    {% endif %}
    {% if team.mon2_shadow == 1%}
        <img src="https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Rocket/shadow_icon.png" alt="shadow" style="position: absolute; top: 0; left: 0; opacity: 0.5;">
        {% endif %}
    </div>
    <div class="column_opp">
    {% if oppban1 == 3 or oppban2 == 3%}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon3}}.png" alt="opp_3" style="filter: grayscale(100%);">
    {% else %}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon3}}.png" alt="opp_3">
    {% endif %}
    {% if team.mon3_shadow == 1%}
        <img src="https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Rocket/shadow_icon.png" alt="shadow" style="position: absolute; top: 0; left: 0; opacity: 0.5;">
        {% endif %}
    </div>
    <div class="column_opp">
    {% if oppban1 == 4 or oppban2 == 4%}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon4}}.png" alt="opp_4" style="filter: grayscale(100%);">
    {% else %}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon4}}.png" alt="opp_4">
    {% endif %}
    {% if team.mon4_shadow == 1%}
        <img src="https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Rocket/shadow_icon.png" alt="shadow" style="position: absolute; top: 0; left: 0; opacity: 0.5;">
        {% endif %}
    </div>
  </div>
  <div class="row">
    <div class="column_opp">
    {% if oppban1 == 5 or oppban2 == 5%}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon5}}.png" alt="opp_5" style="filter: grayscale(100%);">
    {% else %}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon5}}.png" alt="opp_5">
    {% endif %}
    {% if team.mon5_shadow == 1%}
        <img src="https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Rocket/shadow_icon.png" alt="shadow" style="position: absolute; top: 0; left: 0; opacity: 0.5;">
        {% endif %}
    </div>
    <div class="column_opp">
    {% if oppban1 == 6 or oppban2 == 6%}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon6}}.png" alt="opp_6" style="filter: grayscale(100%);">
    {% else %}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon6}}.png" alt="opp_6">
    {% endif %}
    {% if team.mon6_shadow == 1%}
        <img src="https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Rocket/shadow_icon.png" alt="shadow" style="position: absolute; top: 0; left: 0; opacity: 0.5;">
        {% endif %}
    </div>
    <div class="column_opp">
    {% if oppban1 == 7 or oppban2 == 7%}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon7}}.png" alt="opp_7" style="filter: grayscale(100%);">
    {% else %}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon7}}.png" alt="opp_7">
    {% endif %}
    {% if team.mon7_shadow == 1%}
        <img src="https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Rocket/shadow_icon.png" alt="shadow" style="position: absolute; top: 0; left: 0; opacity: 0.5;">
        {% endif %}
    </div>
    <div class="column_opp">
    {% if oppban1 == 8 or oppban2 == 8%}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon8}}.png" alt="opp_8" style="filter: grayscale(100%);">
    {% else %}
        <img src="https://img.pokemondb.net/sprites/home/normal/{{team.mon8}}.png" alt="opp_8">
    {% endif %}
    {% if team.mon8_shadow == 1%}
        <img src="https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Rocket/shadow_icon.png" alt="shadow" style="position: absolute; top: 0; left: 0; opacity: 0.5;">
        {% endif %}
    </div>
  </div>
</div>
  </li>
  {% endfor %}
</ul>
{% if subm == 1 %}
{% if submitted == 0 %}
<div>
      <form action="{{ url_for('views.tourney') }}" onsubmit="return confirmSubmit()" method="POST">
<label for="form-2" style="font-size: 20px;">How many battles did you win:</label>
    <input type="hidden" name="form_type" value="form2">
    <select name="form-type" id="form2" style="font-size: 20px; padding: 10px;">
      {% if opponent != user %}
      <option value="0">0</option>
      <option value="1">1</option>
      <option value="2">2</option>
      {% endif %}
<!--         Showing only 3 for the user who is getting a bye -->
      <option value="3">3</option>
    </select>
    <br><br>
    <button type="submit">Submit</button>
  </form>
</div>
{% endif %}
{% endif %}
  <script>
    // JavaScript code here
    var columnElements = document.getElementsByClassName("column");
    var blurCount = 0;
    var blurredImages = [];

    Array.from(columnElements).forEach(function(columnElement) {
      var imageElement = columnElement.querySelector("img");

      columnElement.addEventListener("click", function() {
        if (blurCount < 2 || blurredImages.includes(imageElement)) {
          if (blurredImages.includes(imageElement)) {
            imageElement.style.filter = "none";
            blurredImages = blurredImages.filter(function(img) {
              return img !== imageElement;
            });
            blurCount--;
          } else {
            imageElement.style.filter = "blur(5px)";
            blurredImages.push(imageElement);
            blurCount++;
          }

          updateSubmitButton();
        }
      });
    });

    function updateSubmitButton() {
      var submitBtn = document.getElementById("submitBtn");
      if (blurCount === 2) {
        submitBtn.disabled = false;
      } else {
        submitBtn.disabled = true;
      }
    }

    function submitForm1() {
        var hiddenForm = document.getElementById("form1");
          hiddenForm.querySelector("input[name='selectedImages']").value = JSON.stringify(blurredImages.map(function(img) {
            return img.alt;
          }));
      // Perform necessary operations for Button 1
      document.getElementById('form1').submit();
    }
    function confirmSubmit() {
  if (confirm("Are you sure you want to submit scores?")) {
    return true;  // Proceed with form submission
  } else {
    return false; // Cancel form submission
  }
}
  </script>
<form id="form1" action="{{ url_for('views.tourney') }}" method="POST" style="display: none;">
    <input type="hidden" name="form_type" value="form1">
     <input type="hidden" name="selectedImages">
  </form>
{% endblock %}